/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) twip_impl_dae_fun_jac_x_xdot_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[24] = {6, 6, 0, 0, 3, 3, 7, 11, 15, 3, 4, 5, 0, 3, 4, 5, 1, 3, 4, 5, 2, 3, 4, 5};
static const casadi_int casadi_s4[15] = {6, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[3] = {6, 0, 0};

/* twip_impl_dae_fun_jac_x_xdot_z:(i0[6],i1[6],i2[2],i3[],i4[])->(o0[6],o1[6x6,15nz],o2[6x6,6nz],o3[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][3] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a2=arg[0]? arg[0][4] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a3=arg[0]? arg[0][5] : 0;
  a0=(a0-a3);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][3] : 0;
  a4=6.1670000000000003e-02;
  a5=4.1819999999999996e-02;
  a6=-2.2497000000000010e-02;
  a7=arg[0]? arg[0][1] : 0;
  a8=sin(a7);
  a8=(a6*a8);
  a9=sin(a7);
  a10=(a8*a9);
  a5=(a5-a10);
  a10=(a4*a5);
  a11=1.5417500000000001e-01;
  a12=2.0000000000000001e-01;
  a13=cos(a7);
  a13=(a12*a13);
  a14=casadi_sq(a13);
  a14=(a11-a14);
  a15=(a5*a14);
  a10=(a10/a15);
  a16=10.;
  a17=arg[2]? arg[2][0] : 0;
  a18=(a16*a17);
  a19=arg[2]? arg[2][1] : 0;
  a16=(a16*a19);
  a18=(a18+a16);
  a16=-2.0000000000000001e-01;
  a20=(a16*a2);
  a21=sin(a7);
  a22=(a20*a21);
  a23=(a22*a2);
  a24=(a16*a3);
  a25=sin(a7);
  a26=(a24*a25);
  a27=(a26*a3);
  a23=(a23+a27);
  a27=-1.9999999999999996e-01;
  a27=(a27*a1);
  a28=2.0000000000000000e-02;
  a29=(a28*a2);
  a27=(a27+a29);
  a23=(a23+a27);
  a18=(a18-a23);
  a23=(a10*a18);
  a27=(a13*a5);
  a27=(a27/a15);
  a29=-5.7503000000000005e-02;
  a30=(a29*a3);
  a31=sin(a7);
  a32=(a30*a31);
  a33=cos(a7);
  a34=(a32*a33);
  a35=(a34*a3);
  a36=-1.9600000000000002e+00;
  a37=sin(a7);
  a37=(a36*a37);
  a35=(a35+a37);
  a37=(a28*a1);
  a38=-2.0000000000000000e-03;
  a39=(a38*a2);
  a37=(a37+a39);
  a35=(a35+a37);
  a37=(a17+a19);
  a35=(a35+a37);
  a37=(a27*a35);
  a23=(a23+a37);
  a0=(a0-a23);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][4] : 0;
  a23=(a13*a5);
  a23=(a23/a15);
  a37=(a23*a18);
  a39=2.5000000000000000e+00;
  a40=(a39*a5);
  a40=(a40/a15);
  a41=(a40*a35);
  a37=(a37+a41);
  a0=(a0+a37);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][5] : 0;
  a37=casadi_sq(a13);
  a11=(a11-a37);
  a11=(a11/a15);
  a19=(a19-a17);
  a17=(a12*a3);
  a37=sin(a7);
  a41=(a17*a37);
  a42=(a41*a1);
  a43=5.7503000000000005e-02;
  a44=(a43*a3);
  a45=sin(a7);
  a46=(a44*a45);
  a47=cos(a7);
  a48=(a46*a47);
  a49=(a48*a2);
  a42=(a42+a49);
  a49=(a43*a2);
  a50=sin(a7);
  a51=(a49*a50);
  a52=cos(a7);
  a53=(a51*a52);
  a54=(a53*a3);
  a42=(a42+a54);
  a54=(a38*a3);
  a42=(a42+a54);
  a19=(a19-a42);
  a42=(a11*a19);
  a0=(a0-a42);
  if (res[0]!=0) res[0][5]=a0;
  a0=cos(a7);
  a30=(a30*a0);
  a30=(a33*a30);
  a0=sin(a7);
  a32=(a32*a0);
  a30=(a30-a32);
  a30=(a3*a30);
  a32=cos(a7);
  a36=(a36*a32);
  a30=(a30+a36);
  a36=(a27*a30);
  a32=sin(a7);
  a32=(a12*a32);
  a0=(a5*a32);
  a42=cos(a7);
  a6=(a6*a42);
  a9=(a9*a6);
  a6=cos(a7);
  a8=(a8*a6);
  a9=(a9+a8);
  a8=(a13*a9);
  a0=(a0+a8);
  a0=(a0/a15);
  a8=(a27/a15);
  a6=(a13+a13);
  a6=(a6*a32);
  a6=(a5*a6);
  a14=(a14*a9);
  a6=(a6-a14);
  a8=(a8*a6);
  a0=(a0+a8);
  a0=(a35*a0);
  a36=(a36-a0);
  a4=(a4*a9);
  a4=(a4/a15);
  a0=(a10/a15);
  a0=(a0*a6);
  a4=(a4+a0);
  a4=(a18*a4);
  a0=cos(a7);
  a20=(a20*a0);
  a20=(a2*a20);
  a0=cos(a7);
  a24=(a24*a0);
  a24=(a3*a24);
  a20=(a20+a24);
  a24=(a10*a20);
  a4=(a4+a24);
  a36=(a36-a4);
  a36=(-a36);
  if (res[1]!=0) res[1][0]=a36;
  a30=(a40*a30);
  a39=(a39*a9);
  a39=(a39/a15);
  a36=(a40/a15);
  a36=(a36*a6);
  a39=(a39+a36);
  a35=(a35*a39);
  a30=(a30-a35);
  a5=(a5*a32);
  a9=(a13*a9);
  a5=(a5+a9);
  a5=(a5/a15);
  a9=(a23/a15);
  a9=(a9*a6);
  a5=(a5+a9);
  a18=(a18*a5);
  a20=(a23*a20);
  a18=(a18+a20);
  a30=(a30-a18);
  if (res[1]!=0) res[1][1]=a30;
  a13=(a13+a13);
  a13=(a13*a32);
  a13=(a13/a15);
  a15=(a11/a15);
  a15=(a15*a6);
  a13=(a13-a15);
  a19=(a19*a13);
  a13=cos(a7);
  a17=(a17*a13);
  a17=(a1*a17);
  a13=cos(a7);
  a44=(a44*a13);
  a44=(a47*a44);
  a13=sin(a7);
  a46=(a46*a13);
  a44=(a44-a46);
  a44=(a2*a44);
  a17=(a17+a44);
  a44=cos(a7);
  a49=(a49*a44);
  a49=(a52*a49);
  a7=sin(a7);
  a51=(a51*a7);
  a49=(a49-a51);
  a49=(a3*a49);
  a17=(a17+a49);
  a17=(a11*a17);
  a19=(a19-a17);
  a19=(-a19);
  if (res[1]!=0) res[1][2]=a19;
  a19=-1.;
  if (res[1]!=0) res[1][3]=a19;
  a17=1.9999999999999996e-01;
  a49=(a17*a10);
  a51=(a28*a27);
  a49=(a49+a51);
  a49=(-a49);
  if (res[1]!=0) res[1][4]=a49;
  a17=(a17*a23);
  a49=(a28*a40);
  a17=(a17+a49);
  if (res[1]!=0) res[1][5]=a17;
  a41=(a11*a41);
  if (res[1]!=0) res[1][6]=a41;
  if (res[1]!=0) res[1][7]=a19;
  a41=(a38*a27);
  a21=(a16*a21);
  a21=(a2*a21);
  a21=(a21+a22);
  a21=(a21+a28);
  a28=(a10*a21);
  a41=(a41-a28);
  a41=(-a41);
  if (res[1]!=0) res[1][8]=a41;
  a41=(a38*a40);
  a21=(a23*a21);
  a41=(a41-a21);
  if (res[1]!=0) res[1][9]=a41;
  a50=(a43*a50);
  a52=(a52*a50);
  a52=(a3*a52);
  a48=(a48+a52);
  a48=(a11*a48);
  if (res[1]!=0) res[1][10]=a48;
  if (res[1]!=0) res[1][11]=a19;
  a29=(a29*a31);
  a33=(a33*a29);
  a33=(a3*a33);
  a33=(a33+a34);
  a27=(a27*a33);
  a16=(a16*a25);
  a3=(a3*a16);
  a3=(a3+a26);
  a10=(a10*a3);
  a27=(a27-a10);
  a27=(-a27);
  if (res[1]!=0) res[1][12]=a27;
  a40=(a40*a33);
  a23=(a23*a3);
  a40=(a40-a23);
  if (res[1]!=0) res[1][13]=a40;
  a12=(a12*a37);
  a1=(a1*a12);
  a43=(a43*a45);
  a47=(a47*a43);
  a2=(a2*a47);
  a1=(a1+a2);
  a1=(a1+a53);
  a1=(a1+a38);
  a11=(a11*a1);
  if (res[1]!=0) res[1][14]=a11;
  a11=1.;
  if (res[2]!=0) res[2][0]=a11;
  if (res[2]!=0) res[2][1]=a11;
  if (res[2]!=0) res[2][2]=a11;
  if (res[2]!=0) res[2][3]=a11;
  if (res[2]!=0) res[2][4]=a11;
  if (res[2]!=0) res[2][5]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int twip_impl_dae_fun_jac_x_xdot_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int twip_impl_dae_fun_jac_x_xdot_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int twip_impl_dae_fun_jac_x_xdot_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void twip_impl_dae_fun_jac_x_xdot_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int twip_impl_dae_fun_jac_x_xdot_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void twip_impl_dae_fun_jac_x_xdot_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void twip_impl_dae_fun_jac_x_xdot_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void twip_impl_dae_fun_jac_x_xdot_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int twip_impl_dae_fun_jac_x_xdot_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int twip_impl_dae_fun_jac_x_xdot_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real twip_impl_dae_fun_jac_x_xdot_z_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* twip_impl_dae_fun_jac_x_xdot_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* twip_impl_dae_fun_jac_x_xdot_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* twip_impl_dae_fun_jac_x_xdot_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* twip_impl_dae_fun_jac_x_xdot_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int twip_impl_dae_fun_jac_x_xdot_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
