/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) twip_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* twip_impl_dae_fun:(i0[6],i1[6],i2[2],i3[],i4[])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][3] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a2=arg[0]? arg[0][4] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a3=arg[0]? arg[0][5] : 0;
  a0=(a0-a3);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][3] : 0;
  a4=6.1670000000000003e-02;
  a5=4.1819999999999996e-02;
  a6=-2.2497000000000010e-02;
  a7=arg[0]? arg[0][1] : 0;
  a8=sin(a7);
  a6=(a6*a8);
  a8=sin(a7);
  a6=(a6*a8);
  a5=(a5-a6);
  a4=(a4*a5);
  a6=1.5417500000000001e-01;
  a8=2.0000000000000001e-01;
  a9=cos(a7);
  a9=(a8*a9);
  a10=casadi_sq(a9);
  a10=(a6-a10);
  a10=(a5*a10);
  a4=(a4/a10);
  a11=10.;
  a12=arg[2]? arg[2][0] : 0;
  a13=(a11*a12);
  a14=arg[2]? arg[2][1] : 0;
  a11=(a11*a14);
  a13=(a13+a11);
  a11=-2.0000000000000001e-01;
  a15=(a11*a2);
  a16=sin(a7);
  a15=(a15*a16);
  a15=(a15*a2);
  a11=(a11*a3);
  a16=sin(a7);
  a11=(a11*a16);
  a11=(a11*a3);
  a15=(a15+a11);
  a11=-1.9999999999999996e-01;
  a11=(a11*a1);
  a16=2.0000000000000000e-02;
  a17=(a16*a2);
  a11=(a11+a17);
  a15=(a15+a11);
  a13=(a13-a15);
  a4=(a4*a13);
  a15=(a9*a5);
  a15=(a15/a10);
  a11=-5.7503000000000005e-02;
  a11=(a11*a3);
  a17=sin(a7);
  a11=(a11*a17);
  a17=cos(a7);
  a11=(a11*a17);
  a11=(a11*a3);
  a17=-1.9600000000000002e+00;
  a18=sin(a7);
  a17=(a17*a18);
  a11=(a11+a17);
  a16=(a16*a1);
  a17=-2.0000000000000000e-03;
  a18=(a17*a2);
  a16=(a16+a18);
  a11=(a11+a16);
  a16=(a12+a14);
  a11=(a11+a16);
  a15=(a15*a11);
  a4=(a4+a15);
  a0=(a0-a4);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][4] : 0;
  a4=(a9*a5);
  a4=(a4/a10);
  a4=(a4*a13);
  a13=2.5000000000000000e+00;
  a13=(a13*a5);
  a13=(a13/a10);
  a13=(a13*a11);
  a4=(a4+a13);
  a0=(a0+a4);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][5] : 0;
  a9=casadi_sq(a9);
  a6=(a6-a9);
  a6=(a6/a10);
  a14=(a14-a12);
  a8=(a8*a3);
  a12=sin(a7);
  a8=(a8*a12);
  a8=(a8*a1);
  a1=5.7503000000000005e-02;
  a12=(a1*a3);
  a10=sin(a7);
  a12=(a12*a10);
  a10=cos(a7);
  a12=(a12*a10);
  a12=(a12*a2);
  a8=(a8+a12);
  a1=(a1*a2);
  a2=sin(a7);
  a1=(a1*a2);
  a7=cos(a7);
  a1=(a1*a7);
  a1=(a1*a3);
  a8=(a8+a1);
  a17=(a17*a3);
  a8=(a8+a17);
  a14=(a14-a8);
  a6=(a6*a14);
  a0=(a0-a6);
  if (res[0]!=0) res[0][5]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int twip_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int twip_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int twip_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void twip_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int twip_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void twip_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void twip_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void twip_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int twip_impl_dae_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int twip_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real twip_impl_dae_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* twip_impl_dae_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* twip_impl_dae_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* twip_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* twip_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int twip_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
